---
- name: Конфигурация окружения STAGE
  hosts: lf-app2
  gather_facts: true
  become: true

  tasks:
    - name: Изменить имя хоста (Hostname) на сервере
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
